document.querySelector('#newtab-btn').onclick = newTab
document.querySelector('#replace-btn').onclick = replaceTab
document.querySelector('#dup-btn').onclick = dupTab
// document.querySelector('#inspect-btn').onclick = inspectTab
document.querySelector('#stick-btn').onclick = stickTab
//document.querySelector('#bottom-btn').onclick = bottomTab
document.querySelector('#move-btn').onclick = moveTabs
document.querySelector('#detach-btn').onclick = detachTabs
document.querySelector('#detach-btn').onauxclick = popupTab
document.querySelector('#undo-btn').onclick = undoTab
document.querySelector('#closetab-btn').onclick = closeCurTab
// document.querySelector('#hide-sidebar-btn').onclick = hideSidebar
// document.querySelector('#prevtab-btn').onclick = prevTab
// document.querySelector('#group-btn').onclick = groupTabs
// document.querySelector('#up-btn').onclick = upTab
// document.querySelector('#up-btn').onauxclick = topTab
document.querySelector('#down-btn').onclick = downTab
document.querySelector('#down-btn').onauxclick = upTab
document.querySelector('#down-btn').ondblclick = bottomTab
// document.querySelector('#zoom-btn').onclick = zoomPage
document.querySelector('#archiveorg-btn').onclick = archivePage
// document.querySelector('#archiveorg-btn').onclick = archiveOrgPage
document.querySelector('#paste-btn').onclick = newTabWithUrl
document.querySelector('#search-btn').onclick = searchTab
