document.querySelector('#newtab-btn').onclick = newTab
document.querySelector('#replace-btn').onclick = replaceTab
document.querySelector('#dup-btn').onclick = dupTab
// document.querySelector('#inspect-btn').onclick = inspectTab
document.querySelector('#stick-btn').onclick = stickTab
document.querySelector('#bottom-btn').onclick = bottomTab
document.querySelector('#detach-btn').onclick = detachTab
document.querySelector('#undo-btn').onclick = undoTab
// document.querySelector('#close-cur-btn').onclick = closeCurTab
// document.querySelector('#hide-sidebar-btn').onclick = hideSidebar
document.querySelector('#prevtab-btn').onclick = prevTab
document.querySelector('#group-btn').onclick = groupTabs
